version: '3.1'

services:

  wordpress:
    image: wordpress:${LOCAL_WP-5.8}-php${LOCAL_PHP-7.4}
    restart: always
    ports:
      - ${LOCAL_PORT-8080}:80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_DEBUG_DISPLAY', true );
    user: "33:33"
    depends_on:
      - mysql
    volumes:
      - wp:/var/www/html:rw
      - ./:/var/www/html/wp-content/plugins/wp-crontrol

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - mysql:/var/lib/mysql:rw

  wpcli:
    image: wordpress:cli-php${LOCAL_PHP-7.4}
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    user: "33:33"
    depends_on:
      - mysql
    init: true
    volumes:
      - wp:/var/www/html:rw

volumes:
  wp:
  mysql:
