version: '3.1'

services:

  wordpress:
    image: wordpress:${LOCAL_WP-5.8}-php${LOCAL_PHP-7.4}
    restart: always
    ports:
      - ${LOCAL_PORT-8080}:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wp:/var/www/html
      - ./:/var/www/html/wp-content/plugins/wp-crontrol

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

  cli:
    image: wordpress:cli-php${LOCAL_PHP-7.4}
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    init: true
    volumes:
      - wp:/var/www/html

volumes:
  wp:
  db:
