version: '3.1'

services:

  wordpress:
    image: wordpress:${LOCAL_WP-5.8}-php${LOCAL_PHP-7.4}
    restart: always
    networks:
      - wp-crontrol
    ports:
      - ${LOCAL_PORT-8080}:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./tests/wordpress:/var/www/html

  db:
    image: mysql:latest
    restart: always
    networks:
      - wp-crontrol
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  db:

networks:
  wp-crontrol:
    driver: bridge
