# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Build Release
on:
  push:
    branches:
      - 'release'

jobs:
  wordpress:
    name: Release
    runs-on: ubuntu-18.04
    timeout-minutes: 10
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install PHP
      uses: shivammathur/setup-php@2.20.1
      with:
        php-version: 8.0
        coverage: none
      env:
        fail-fast: true

    - name: Debugging
      run: |
        php --version
        composer --version

    - name: Generate autoload file
      run: composer dump-autoload --no-dev

    - name: Setup
      run: 'echo "VERSION=$(grep -Po ''\"version\": \"[0-9\\.]+\"'' package.json | grep -Po ''[0-9\\.]+'')" >> $GITHUB_ENV'

    - name: Tag
      run: |
        echo "Releasing version $VERSION ..."
        git config user.name github-actions
        git config user.email github-actions@github.com
        git checkout -b "release-$VERSION"
        git add -f vendor/autoload.php
        git add -f vendor/composer/*
        git commit -m "Release $VERSION"
        git tag "$VERSION"
        git push --tags
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
