name: Deploy Tag
on:
  push:
    tags-ignore:
      - '*alpha*'
      - '*beta*'
      - '*rc*'

jobs:
  wordpress:
    name: WordPress.org
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1

    - name: WordPress Plugin Deploy
      uses: 10up/action-wordpress-plugin-deploy@1.4.1
      env:
        SVN_USERNAME: ${{ secrets.WPORG_SVN_USERNAME }}
        SVN_PASSWORD: ${{ secrets.WPORG_SVN_PASSWORD }}
