# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Functional Tests
on:
  push:
    branches:
      - 'develop'
      - 'trunk'
      - 'master'
  pull_request:
    branches:
      - '**'
  # Once weekly on Wednesdays at 16:00 UTC.
  schedule:
    - cron: '0 16 * * 3'
  workflow_dispatch:

jobs:
  e2e:
    strategy:
      matrix:
        wp: ['5.8','5.6','nightly']
        php: ['8.0','7.4']
        include:
          - wp: '5.8'
            php: '8.1'
          - wp: 'nightly'
            php: '8.1'
      fail-fast: false
    name: WP ${{ matrix.wp }} / PHP ${{ matrix.php }}
    runs-on: ubuntu-18.04
    timeout-minutes: 10
    env:
      LOCAL_WP: ${{ matrix.wp == 'nightly' && '5.8' || matrix.wp }}
      LOCAL_PHP: ${{ matrix.php }}
      LOCAL_WP_DEBUG: ${{ matrix.php != '8.1' && 1 || 0 }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1

    - name: Get Composer cache directory
      id: composer-cache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"

    - name: Composer cache
      uses: actions/cache@v2
      env:
        cache-name: cache-composer-dependencies
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: 7.4-composer-${{ hashFiles('composer.json') }}

    - name: Install PHP
      uses: shivammathur/setup-php@2.7.0
      with:
        php-version: 7.4
        coverage: none
      env:
        fail-fast: true

    - name: Debugging
      run: |
        php --version
        composer --version
        docker --version
        docker-compose --version

    - name: Start Docker environment
      run: |
        composer test:start

    - name: Log running Docker containers
      run: docker ps -a

    - name: Install dependencies
      run: |
        composer install --prefer-dist

    - name: Update to nightly
      if: ${{ matrix.php == 'nightly' }}
      run: |
        docker-compose run --rm wpcli wp core download --force --version=nightly

    - name: Debug WordPress version
      continue-on-error: true
      run: docker-compose run --rm wpcli wp core version

    - name: Run the tests
      run: composer test:ft

    - name: Upload test artifacts
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: e2e-wp-${{ matrix.wp }}-php-${{ matrix.php }}
        path: tests/_output
